# Generated by Django 4.0 on 2022-01-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
        ('MedSchedulerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('time', models.TimeField()),
                ('is_taken', models.BooleanField(default=False)),
                ('presciption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedSchedulerApp.presciption')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedSchedulerApp.schedule')),
            ],
        ),
    ]
