# Generated by Django 4.0 on 2022-01-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedSchedulerApp', '0002_schedule_scheduleelement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presciption',
            old_name='account',
            new_name='user',
        ),
    ]
