# Generated by Django 4.0 on 2022-01-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0002_remove_profile_phone_number'),
        ('MedSchedulerApp', '0004_rename_presciption_scheduleelement_prescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presciption',
            new_name='Prescription',
        ),
    ]
